version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github:
        patterns:
          - "actions/*"

  - package-ecosystem: "pip"
    directory: "/"
    groups:
      flake8:
        patterns:
          - "flake8*"
          - "Flake8-pyproject"
      pytest:
        patterns:
          - "pytest*"
      sphinx:
        patterns:
          - "sphinx"
          - "sphinxcontrib-*"
      types:
        patterns:
          - "types-*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50
